server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:mem:test #메모리DB 그리서 서버다시시작하면 무조건 다시 만들어짐
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #none update create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
